image:
  repository: registry.gitlab.com/falabella-gitlab/catalyst/core/platform-services/development/master-data-service

replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  uriPrefix: /master-data/
  hosts:
    - commerce-platform.osmos.services
    - www.osmos.services

jwt_policy:
  enabled: true
  mtls: true
  identity:
    - name: auth0
      audience: "https://osmos.services"
      issuer: "https://osmos.auth0.com/"
      uri: "https://osmos.auth0.com/.well-known/jwks.json"
      excluded_path:
        prefix: "/metrics"

containers:
  port: 4444

environment:
  name: production

pod:
  initialDelaySeconds: 30

gcp:
  enabled: true

database:
  enabled: true

environmentVariables: 
  NODE_ENV: "production"
  FORCE_NO_STACKDRIVER_DEBUG: true

service:
  type: ClusterIP
  port: 80  
