image:
  repository: # Need to put image repo name url
replicaCount: 1

ingress:
  enabled: true
  uriPrefix: /catalog/
  hosts:
    - dev.adidas.services  #Adding some sample url

containers:
  port: 4444

environment:
  name: dev

pod:
  initialDelaySeconds: 30

gcp:
  enabled: true

database:
  enabled: true

environmentVariables: 
  NODE_ENV: "dev"

service:
  type: ClusterIP
  port: 80  
